using System;
using System.ComponentModel;

namespace School.Entities
{
	/// <summary>
	///		The data structure representation of the 'Classes' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IClasses 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Classes"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// ClassNumber : 
		/// </summary>
		System.String  ClassNumber  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _studentsClassId
		/// </summary>	
		TList<Students> StudentsCollection {  get;  set;}	

		#endregion Data Properties

	}
}


