using System;
using System.ComponentModel;

namespace School.Entities
{
	/// <summary>
	///		The data structure representation of the 'Students' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IStudents 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Students"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// Name : 
		/// </summary>
		System.String  Name  { get; set; }
		
		/// <summary>
		/// Address : 
		/// </summary>
		System.String  Address  { get; set; }
		
		/// <summary>
		/// ClassId : 
		/// </summary>
		System.Int32  ClassId  { get; set; }
		
		/// <summary>
		/// Birthdate : 
		/// </summary>
		System.DateTime  Birthdate  { get; set; }
		
		/// <summary>
		/// Gender : 
		/// </summary>
		System.String  Gender  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


